### PR TITLE
Create PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by hisabimbola**

### CODE REVIEW

**Comment by Siilwyn** [comment]
Looks good, the comment styling isn't consistent though. Would use two dashes and also use the same style for the uppercase and ending of lines as #2.
👍

**Comment by PhilippSpo** [comment]
Why are there underscores in the comments? I don't see them in the Issue template.. is this on purpose?

**Comment by hisabimbola** [comment]
@PhilippSpo The underscores were meant to style the  notes, but afterwards decided to put them as comments so the underscores are kinda useless now, I will remove them.

**Comment by PhilippSpo** [comment]
@hisabimbola they are still there in the description. Also, it would be nice to have all comments start with an uppercase letter (#nitpick) 😜

**Comment by hisabimbola** [comment]
@PhilippSpo Updated.... 😉

**Comment by PhilippSpo** [comment]
👍  LGTM now

**Pull request merged**
